name: magpie_bridge
description: Reliable UDP Relay Network protocol library for Dart.
version: 0.1.0
homepage: https://github.com/moky/magpie-bridge
repository: https://github.com/moky/magpie-bridge
issue_tracker: https://github.com/moky/magpie-bridge/issues

environment:
  sdk: ">=2.19.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
